### ISSUE TITLE
Implement a search option to find a variable within the loaded data

### ISSUE THREAD

**Issue by cpsancha** [ebranlard/pyDatView#111]
It would be nice to have a search bar, or Ctrl+F, to quickly find variables when loading data files with a huge number of variables.

**Comment by ebranlard** [comment]
Dear @cpsancha, 

This feature is already present (#16), and works exactly as you mentioned (using Ctrl+F). 
You can download one of the latest dev versions here: 
         https://github.com/ebranlard/pyDatView/releases/tag/vdev
Let me know if it doesn't work for you.

**Comment by cpsancha** [comment]
Thanks, I'll give it a try. 
Which dev version should I use? v0.2.193 or v0.2.194, as the release date of v193 is later than the one for v194?

**Comment by ebranlard** [comment]
You can use 194, 193 came from a deployment run that stalled.

**Comment by ebranlard** [comment]
I'm closing this issue, feel free to reopen it the feature is not what you expected.
