### ISSUE TITLE
How to pass multiple dataframes at once？

### ISSUE THREAD

**Issue by Damen957** [ebranlard/pyDatView#120]
I need to pass multiple dataframes at once, not one.
For example：`pydatview.show(dataframe=[df1,df2])`

**Comment by Damen957** [comment]
Because each wind turbine needs to be a dataframe, you can drag the wind turbine number to the legend.

**Comment by ebranlard** [comment]
Thanks for your comment, I rarely use the show command this way, the feature you are requesting make a lot of sense. 

I've modified the interface of the `show` function,  now using `dataframes` as a keyword argument. You can pass one dataframe or a list of dataframes to this argument, and also a list of names. 
See this example below:
```python
import pydatview 
import numpy as np
import pandas as pd
df1 = pd.DataFrame(data={'ColA': np.linspace(0,1,100)+1,'ColB': np.random.normal(0,1,100)+0})
df2 = pd.DataFrame(data={'ColA': np.linspace(0,1,100)+1,'ColB': np.random.normal(0,1,100)+0})

pydatview.show(dataframes=[df1,df2], names=['WT1','WT2'])
pydatview.show([df1,df2])
pydatview.show(df1)

# For files:
#pydatview.show(filenames=['file.csv','file2.csv'])
#pydatview.show(['file.csv','file2.csv'])
#pydatview.show('file.csv')
```

Let me know if this address your issue. I've pushed the changes in the dev branch.

**Comment by Damen957** [comment]
> Thanks for your comment, I rarely use the show command this way (I'm using the GUI/App directly), but the feature you are requesting make a lot of sense.
> 
> I've modified the interface of the `show` function, now using `dataframes` as a keyword argument. You can pass one dataframe or a list of dataframes to this argument, and also a list of names. See this example below:
> 
> ```python
> import pydatview 
> import numpy as np
> import pandas as pd
> df1 = pd.DataFrame(data={'ColA': np.linspace(0,1,100)+1,'ColB': np.random.normal(0,1,100)+0})
> df2 = pd.DataFrame(data={'ColA': np.linspace(0,1,100)+1,'ColB': np.random.normal(0,1,100)+0})
> 
> pydatview.show(dataframes=[df1,df2], names=['WT1','WT2'])
> pydatview.show([df1,df2])
> pydatview.show(df1)
> 
> # For files:
> #pydatview.show(filenames=['file.csv','file2.csv'])
> #pydatview.show(['file.csv','file2.csv'])
> #pydatview.show('file.csv')
> ```
> 
> I've pushed the changes in the dev branch. Let me know if this addresses your issue.

@ebranlard  Thanks, this solved my problem.

**Comment by ebranlard** [comment]
Great!
