### ISSUE TITLE
Error with font panel / curve fitting

### ISSUE THREAD

**Issue by SimonHH** [ebranlard/pyDatView#122]
Hi,

after loading a file and clicking the font panel this error is given:
![image](https://user-images.githubusercontent.com/38310787/181283080-5c588a65-97f3-47e7-bfc4-da40cff1ae03.png)

When selecting any options from the tools or data dropdown this errors is given:
![image](https://user-images.githubusercontent.com/38310787/181286072-24a78f7a-9fa4-485c-ab75-b2d36a2567c1.png)
Only exception are the SI and WE conversion options.

As the dependencies are changed recently I suspect a compatibility issue. Any ideas?

I tried the latest dev version v0.3-dev-19.

**Comment by ebranlard** [comment]
Hi Simon, 
Thanks for this report. I can reproduce the issue with scipy, and I'm going to push a fix in the next commit. But I can't reproduce the one with matplotlib. What do you call the "Font Panel"? I'm not sure I was aware of it 
Thanks

**Comment by SimonHH** [comment]
With "Font Panel" I meant the "configure subplots" bottom in the lower left corner:
![image](https://user-images.githubusercontent.com/38310787/181572148-62ea35fc-262e-49e6-b0d0-460966cba7de.png)
Thank you for the support!

**Comment by ebranlard** [comment]
Thanks a lot, I missed that error. I hope it's fixed now. I couldn't check with other OS though.

**Comment by ebranlard** [comment]
Hi @SimonHH 
are you still seeing this with the latest versions of pyDatView?

**Comment by SimonHH** [comment]
All good on my side. Thank you for the fix.
