### ISSUE TITLE
Date Format Issue

### ISSUE THREAD

**Issue by Carlos-manriqu** [ebranlard/pyDatView#132]
Hi Guys,

I need to plot some data that has date format as dd/mm/yyyy hh:mm but my plots are not right. I manually changed my time format to the US format of mm/dd/yyyy hh:mm and that solved the issue. Since I have a lot of data to process and to share I need to use the original format, is it possible to change the data format?

Thanks

**Comment by ebranlard** [comment]
Hi @Carlos-manriqu 
Could you attach a minimal input file here, I can try to test it and find a way to make it work. My guess it that there is an option to pass to the pandas library to parse it properly. 
Thanks

**Comment by Carlos-manriqu** [comment]
[VHarmonics_05-09 to 09-10.csv](https://github.com/ebranlard/pyDatView/files/10264221/VHarmonics_05-09.to.09-10.csv)
Hi @ebranlard  thanks for the prompt response. File attached

**Comment by ebranlard** [comment]
Hi @Carlos-manriqu 

I've added a popup menu next to the "format' combo box. 
![image](https://user-images.githubusercontent.com/1318316/208677806-d2d5bd14-7439-460b-a4e7-e30f83928f10.png)

If you select "date format: day first", I believe the behavior will be the one you expect. If you've already loaded the data, you'll have to "reload" the first time you use this option. But pyDatView will remember this option on restart and for the next loading of data. 

Can you try the latest dev version, and let me know if it behaves as expected?

Thanks!

**Comment by Carlos-manriqu** [comment]
Hi Mate,

thanks for this. Sorry I did not said earlier. I am not very savvy on how to use github. Awesome work!
