### ISSUE TITLE
file formats with the same extension

### ISSUE THREAD

**Issue by SimonHH** [ebranlard/pyDatView#149]
Hi,
I have more than one file format that has the same file ending.

How do I enable reading of both formats with the format option set to auto?

I would think that the format with the higher priority is tried first and if this causes an error the next file format on the list is used to open the file.
I implemented the WrongFormatError error but this only gives a popup and not the desired behavior.

Any thoughts?

Best regards,
Simon

**Comment by ebranlard** [comment]
Hi @SimonHH 

I'm surprised that it's not working for you, the priority and `WrongFormatError` should indeed work the way you thought about them. 

The `WrongFormatError` is intended to be thrown when the `read` function of a given class detects that the format is quite far off from what's expected by the format definition. The `BrokenFormatError` is thrown when the format looks about right but the user likely misformated something. The distinction between the two can be a bit blurry. 


You can try the following:
- Test the reading of your file with your class, and make sure the `BrokenFormatError` is thrown
    ```from pydatview.io.file_x import FileX. 
       FileX( 'wrongfile.dat'  )
- Test the file format detection (you might want to add a couple of print statements in the `detectFormat` function to debug what's happening:
    ```from pydatview.io import detectFormat
       format, f = detectFormat( ' somefile.dat' )
       print(format)
       print(f)```
       
     
Are you using a user defined format that is placed in the user-pydatview-io directory? (Help>About, e.g.   `C:\Users\XXX\AppData\Roaming\pydatview_io`) 
Maybe there is a pydatview bug for userdefined formats. Let me check..

**Comment by SimonHH** [comment]
Hi @ebranlard,

that helped. I had the WrongFormatError error thrown in the toDataFrame def and not in the read def. Now this works as expected.

FYI: I add the formats not in the user-pydatview-io directory but directly in pydatview\io\ and list them in __init__.py

Best regards,
Simon

**Comment by ebranlard** [comment]
Great! I'm glad it worked out in the end.
