### ISSUE TITLE
how to support Chinese language 

### ISSUE THREAD

**Issue by lizhuang2511** [ebranlard/pyDatView#155]
when I use Chinese language it can not  display  well

**Comment by ebranlard** [comment]
Hi @lizhuang2511, can you describe your problem a bit more, maybe provide an example of input file and a screenshot? 

There is already some check to detect whether chinese characters are needed in pyDatView. 
If chinese characters are detected (using the function `has_chinese_char`, and `needChineseFont`), then the `spcialFont`  is used in `GUIPlotPanel`. You can try to see if indded `needChineseFont` is set to true internally. 

The default special font is the one that is shipped with pyDatView called `SimHei.ttf` located at the root of the pyDatView folder. You an try making a backup of that ttf file, and then replacing if with another ttf file (with the same name `SimHei.ttf`) and see if that helps?
