### ISSUE TITLE
Measuring dates/time

### ISSUE THREAD

**Issue by Carlos-manriqu** [ebranlard/pyDatView#162]
Hi Mate,

it would be great if the measurement section could show the times/dates as proper dates/times instead of numerical value [also the delta x show difference in time]
<img width="859" alt="Screenshot 2023-07-28 115953" src="https://github.com/ebranlard/pyDatView/assets/121005030/4ca86f38-f5ae-4d87-bcab-2574d2d38152">

**Comment by ebranlard** [comment]
Hey, 
Can you provide a small example file for me to test? (5-10 values would be enough) 
Thanks a lot!

**Comment by Carlos-manriqu** [comment]
sure thing
[Processed Data.csv](https://github.com/ebranlard/pyDatView/files/12189826/Processed.Data.csv)

**Comment by ebranlard** [comment]
Dear @Carlos-manriqu 
Thank you for your patience. I've just pushed a commit that should address the issue you were seeing. 
The main issue is that matplolib handles datetimes using it's own numerical representation. So we need to convert these numerical values back to a date format using `matplotlib.dates.date2num`. 

Right now, dates are displayed in a very long format. I've setup a placeholder to change this format in `common.py` `pretty_date`. The idea would be to display a different date format based on the "resolution" and "timespan" of the plot (if the `dt` is in days, no need for the seconds, if the `dt` is in miliseconds, no need for year month, etc.)
But I didn't get to it.

Let me know if it works!
