### ISSUE TITLE
graphic is not updated

### ISSUE THREAD

**Issue by SimonHH** [ebranlard/pyDatView#166]
Hi,

thank you very much for all the improvements!
With implementing it on our end I noticed that pydatview freezes once the window is resized.

Everything below the task bar (file, Data, ...) freezes and is not redrawn.
The dropdown for auto, same table,... is not visible anymore (after some resizing) but the dropdown is shown when clicking the right spot.

Not sure what is causing this. Maybe a replot command is missing somewhere?

Best regards,
Simon

**Comment by ebranlard** [comment]
Hi Simon, 

I couldn't reproduced the issue (I tried version 149). I've now pushed a small update (v150), can you let me know if that fixes it? 

Thanks a lot

**Comment by SimonHH** [comment]
Hi Emmanuel,

interesting. Nevertheless your update seems to fix it. v151 does not show the issue anymore as far as I can see. Thank you!

Best regards,
Simon
