### ISSUE TITLE
Bugs noticed when stress testing dev before NAWEA '23

### ISSUE THREAD

**Issue by mayankchetan** [ebranlard/pyDatView#167]
List of potential bugs found when stress testing the dev branch. Will add to list as more are found.

- [x] If a file is transposed twice, the original signal labels are lost. Screenshot in comment: https://github.com/ebranlard/pyDatView/issues/167#issuecomment-1767320404
- [x] pyDatView freezes if the following sequence of operations are carried out: Select 2 files --> select 2 signals --> right click --> add --> cancel. No issues if we complete adding the new signal. There is no related error message in terminal. Screenshot in comment: https://github.com/ebranlard/pyDatView/issues/167#issuecomment-1767330443.

**Comment by mayankchetan** [comment]
Related to # 1 above

![image](https://github.com/ebranlard/pyDatView/assets/4620557/96a11ae2-ba36-4765-8a3d-e05a6d22ad1a)

**Comment by mayankchetan** [comment]
Related to # 2 above

![image](https://github.com/ebranlard/pyDatView/assets/4620557/2a9104e0-47ba-44e6-b959-464605aa5c36)

**Comment by ebranlard** [comment]
Thank you, feel free to keep adding to the list. 
Bug 2 is now fixed by [ac12adb](https://github.com/ebranlard/pyDatView/commit/ac12adbab5ebf263092bbf4cf086d2a8c7043d52)

**Comment by ebranlard** [comment]
Feel free to reopen if more bugs are found
