### ISSUE TITLE
Run Script does not find pydatview.io installation

### ISSUE THREAD

**Issue by SimonHH** [ebranlard/pyDatView#170]
Hi,

when trying the new script export I noticed, that the run script button does not work because pydatview.io is not found.

See screenshot:
![image](https://github.com/ebranlard/pyDatView/assets/38310787/352e9fa0-66da-4d29-a801-3b7c698b6120)

Not sure how to setup pydatview so that the import works.

**Comment by SimonHH** [comment]
When running in a python command line it works as long as the current path is the pydatview folder.
1. Excel files are imported as dict and not as DataFrame by pydatview.io
2. The order of files seems to be wrong. This is relevant when the selected sensor names between files are not identical.
3. The label is not the one that is displayed inside of pydatview.

**Comment by ebranlard** [comment]
Hi Simon, 

Thank you for reporting this, I can see how these errors can show up. 

For the import of `pydatview.io` to work, the user need to do a `pip install -e .` while in the pydatview folder. If the user used an installer, then the would have to clone the pydatview repository and install it. Or the users can uses some of the other libraries. 
I indeed need to document that! 

I'll try to fix some of the other issues or give more warning that the script might not be "perfect". The main issue, is I can make the script more bulletproof, but at the expense of adding a lot of lines of code, which could discourage the user. But I'll dig into it nonetheless! Thanks a lot for testing and for your bug report!

**Comment by ebranlard** [comment]
Hi Simon, 
I've addressed a bit some of your comments, in particular I've added a Help button and hopefully fixed the issue with the ExcelFile.  Can you check if that works a bit better?

Thanks!

**Comment by ebranlard** [comment]
Hopefully the user can navigate the script running with the new documentation.. But it might not be straightforward.
