### ISSUE TITLE
Matrix function: subplotsPar is not defined

### ISSUE THREAD

**Issue by SimonHH** [ebranlard/pyDatView#171]
When selecting the matrix box I get an error, that subplotsPar is not defined in GUIPlotPanel.py line 686, in setSubplotSpacing.

**Comment by ebranlard** [comment]
Hi @SimonHH 
Thanks for testing and reporting this. I believe I came accross this bug this week and fixed it. Can you check if you are using the latest dev? 
Thanks a lot!
