### ISSUE TITLE
Question about reading TurbSim .bts files

### ISSUE THREAD

**Issue by achilleas101** [ebranlard/pyDatView#185]
Dear @ebranlard,
Thank you for creating this easy to use software and making it open to the public!
I am using pyDatView to visualize a .bts file after running the TurbSim code. Could you please inform me about what procedures are used to make these plots? For example are the u_[m/s]-z [m]

![image](https://github.com/ebranlard/pyDatView/assets/130864550/6279aa7c-4a87-442e-a56b-2341f0a4f710)

and the TI [%]-z [m]

![image1](https://github.com/ebranlard/pyDatView/assets/130864550/397e7eb8-93e3-4045-910b-440dace3fb3e)

 taken from data on a single plane or are they horizontally averaged values?

Thank you for your help in advance!
Best regards,
Achilleas

**Comment by ebranlard** [comment]
Hi, 
Sorry for the delay. The vertical profile data are computed here in `toDataFrame`: 
https://github.com/ebranlard/pyDatView/blob/0eca76713f0ea4cd24275489c236b615872a3f66/pydatview/io/turbsim_file.py#L633

Which in turns point to this function: 
https://github.com/ebranlard/pyDatView/blob/dev/pydatview/io/turbsim_file.py#L367

By default, the argument "full" is used, which means it takes the average over all the "y" values of the box. 
To change the behavior (and get it for the mid plane), you'd have to change the source code. You can also use the TurbSimFile class outside of pydatview and call the function `vertProfile` in a python script. 

I hope that helps!

**Comment by achilleas101** [comment]
Dear @ebranlard ,
Thank you again for the reply! Υοur help was invaluable.

Best regards,
Achilleas
