### ISSUE TITLE
AttributeError: 'str' object has no attribute 'columns'`

### ISSUE THREAD

**Issue by tobimichigan** [ebranlard/pyDatView#53]
pydatview.show('fn.csv')

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-c715a5ee6673> in <module>
----> 1 pydatview.show('fn.csv')

~/pyDatView/pydatview/__init__.py in show(*args, **kwargs)
      6 def show(*args,**kwargs):
      7     from pydatview.pydatview import showApp
----> 8     showApp(*args,**kwargs)
      9 
     10 

~/pyDatView/pydatview/pydatview.py in showApp(dataframe, filenames)
    666         #import time
    667         #tstart = time.time()
--> 668         frame.load_df(dataframe)
    669         #tend = time.time()
    670         #print('PydatView time: ',tend-tstart)

~/pyDatView/pydatview/pydatview.py in load_df(self, df, name, bAdd, bPlot)
    279             self.tabList.append(Table(df=df, name=name))
    280         else:
--> 281             self.tabList = TableList( [Table(df=df, name=name)] )
    282         self.load_tabs_into_GUI(bAdd=bAdd, bPlot=bPlot)
    283         if hasattr(self,'selPanel'):

~/pyDatView/pydatview/Tables.py in __init__(self, data, columns, name, filename, df, fileformat)
    226                 self.name=name
    227             self.data    = df
--> 228             self.columns = self.columnsFromDF(df)
    229         else:
    230             # ndarray??

~/pyDatView/pydatview/Tables.py in columnsFromDF(self, df)
    248 
    249     def columnsFromDF(self,df):
--> 250         return [s.replace('_',' ') for s in df.columns.values.astype(str)]
    251 
    252 

AttributeError: 'str' object has no attribute 'columns'`

Any clues?

**Comment by ebranlard** [comment]
Hey, can you attach your input file (maybe just the 10 first lines would be enough)?

Can you also mention which version of python you are using? I wonder if it's a python2 python 3 issue. 

I must say, I usually use the GUI and not the command line directly, maybe I've broken something. 

Thanks

**Comment by ebranlard** [comment]
I confirm that I broke something, I'll fix it and keep you posted.

**Comment by ebranlard** [comment]
It should be fixed now. Thank you for posting an issue!
