### ISSUE TITLE
Anaconda environment

### ISSUE THREAD

**Issue by tonyinme** [ebranlard/pyDatView#54]
The current installation does not seem to work using a conda environment.
A workaround is to use 'pythonw' instead of 'python.app'

**Comment by ebranlard** [comment]
Interesting, maybe I'll update the `pythonmac file` to use `pythonw` instead. I need to look up what's the difference between the two. 

When you run:
```./pythonmac pyDatView.py```
I believe it picked up `python.app`, but it should report that if it fails, you can try `conda update python.app`. If you want you can try that as well, it used to work on the other Mac I tried.

**Comment by ebranlard** [comment]
can you also report the output of 
`which pythonw`

**Comment by tonyinme** [comment]
I tried that. The problem seems to be related to wx. The standard python and python.app don't support the wx module. The python version pythonw does have this module.

`┌─[Tue Oct 29][lmartin1:~]
└─>source activate manu
(manu) ┌─[Tue Oct 29][lmartin1:~]
└─>which pythonw
/Users/lmartin1/anaconda/envs/manu/bin/pythonw
(manu) ┌─[Tue Oct 29][lmartin1:~]
└─>which python
/Users/lmartin1/anaconda/envs/manu/bin/python
(manu) ┌─[Tue Oct 29][lmartin1:~]
└─>which python.app
/Users/lmartin1/anaconda/envs/manu/bin/python.app`

**Comment by ebranlard** [comment]
It seems to be working last time we looked at it together. Let's open this again if you still have issues.
