### ISSUE TITLE
figure display

### ISSUE THREAD

**Issue by zz17635** [ebranlard/pyDatView#65]
Hi. By default, the power number is sometimes hidden. Perhaps it would be good to adjust the initial subplot parameters to leave enough margin. Thanks for the software.

![image](https://user-images.githubusercontent.com/68292529/88082217-5f629900-cb79-11ea-9e40-96e1f99eed66.png)

![image](https://user-images.githubusercontent.com/68292529/88082352-98027280-cb79-11ea-9dcb-97e55022a5d0.png)

**Comment by ebranlard** [comment]
Thanks for posting this, I've been annoyed by that as well, it is unfortunately a function of the window size. I'll try to find a way to fix this (it might take some weeks).

**Comment by ebranlard** [comment]
I'm also noticing that your mono font appears different from what I'm used to. I'm not sure why.. I'm hoping one day to have more options to set these up.

**Comment by zz17635** [comment]
> I'm also noticing that your mono font appears different from what I'm used to. I'm not sure why.. I'm hoping one day to have more options to set these up.

possibly because my windows display language is not english

**Comment by ebranlard** [comment]
You can now click the "Home" button of the plot toolbar to trigger a "tight layout", which should make the text above the figure visible. 

Also, the adjustements of the subplot parameters (via plot toolbar) are now remembered on replot. 

I'm closing this issue for now.
