### ISSUE TITLE
For Windows, setup.exe is missing wxpython

### ISSUE THREAD

**Issue by SamWilson22** [ebranlard/pyDatView#66]
For windows, I think the package wxpython is missing from pyDatView_v0.2_setup.exe. When I ran setup.exe and tried to use pyDatView, I was told I was missing the module wx. Once I used: 
```bash
pip install -r requirements.txt
```
the wxpython package installs and pyDatView now works for the most part.

**Comment by ebranlard** [comment]
Hi Sam, I think you might be confused between  the two installation approach: 
  - you can download setup.exe and execute it, then look for "pyDatView" in your windows start menu. 
  -  you can clone the repository, and then install the requirements. 

When you use setup.exe, pyDatView, python and the wx packages are installed in the directory you specify (typically C:/users/ )

Let me know if you still have an issue.  I'll recommend using the 'dev' release setup.exe that you can find in the "releases" tab of github, it will have more features than the v0.2. 

Cheers
