### ISSUE TITLE
Subplot matrix

### ISSUE THREAD

**Issue by lobinho** [ebranlard/pyDatView#67]
Hi there,

first of all thanks for the tool. It's a great one.

I am currently working on an option to put any selected signal on any subplot. Currently, for subplots this is so to speak an eye-matrix, putting one signal on its own subplot. Also I want to add the option of plotting to the left- or right axis. For that I would add a matrix of buttons where each one has three possible states: left, right, none. I will create a feature branch once done. I hope this makes sense.
Cheers

**Comment by ebranlard** [comment]
Implemented in #68
