### ISSUE TITLE
Strategy for GUI Plot Options

### ISSUE THREAD

**Issue by ebranlard** [ebranlard/pyDatView#71]
We have to think about some kind of strategy for the user interface since it might become too crowded for newcomers. In general, I do like that we don't need to click in a bunch of menus, I want it to be a fast debugging/plotting tool, but with more and more features, it might get a bit ugly. 

Here's an attempt to categorize the options:
- plot types (Regular, PDF, FFT, ...) that changes the values of what's on the plot

- curve types (Scatter, StepPlot): that changes the look of the curves

- basic esthetics (Grid, Legend, Log-x, log-y): that changes how the plot looks

- handling of multiple plots (SubPlots, Matrix)

- plot area handling (CrossHair, Annotate, Home, Pan, Spacing options) 

- plot behavior (Autoscale, Sync-x)

- Save button

- info outputs (x=.., y=..)

- Advanced esthetics (placement of the legend, font size, markers / line style / line colors for each plot). 

I consider advanced esthetics as secondary, and I think it's fair to put those in a separate menu (extra click) or tab.  

The standard "Home|Pan|Sliders|Save" takes a lot of space, and is hard to customize. I've already hacked this class, maybe we could hack it even further. 

A toolbar with icons could be a good option, I'm not sure if the icons would be as intuitive as the text. 

A free UI design tool could be nice to prototype options..
some attempts:
https://wireframe.cc/3TC5cf   (not sure if that's editable)

https://ninjamock.com/s/39D35Gx (I can share edit rights if I have email)

**Comment by lobinho** [comment]
Regarding standard toolbar: we could split the icons in two rows which would still fit in height. This would save some horizontal space. If you like that idea, I can add it.

Also, another idea could be adding two buttons to 'Store current view' and 'Restore view'? Together this could be in first row 'Home | Pan | Sliders' and in second 'Save | Store view | Restore view' maybe? Alternatively maybe the standard 'Previous view' / 'Next view' could be handy to fill the second row? But we should probably stick to tools we really need..

**Comment by ebranlard** [comment]
If you know how to split the standard toolbar, yes I think it could be a good idea. An option would be to completely override this toolbar and create our own toolbar(s) with a combination of these standard tools, and the other options. But I'm already hacking it quite a bit, which always scares me if there is an update of matplotlib. 

I had removed the Previous/Next views, because I never really used it, and it was taking space. I'd probably still be in favor of not including them to save space, but I don't have a strong opinion.

**Comment by lobinho** [comment]
What can easily be done is using two hacked toolbars as you had them and arrange them vertically to be 2x2 instead of currently 1x4. This would still have the drawbacks you mentioned though. I can put that on my todo-list.

Okay, no problem with the prev/next view. I just wanted to give it a thought.

**Comment by ebranlard** [comment]
I'm going to introduce an "Esthetics" Panel for options such as : placement of the legend, font size, markers size,  and maybe one day line style / line colors for each plot. 

I thought of doing a Notebook, where one tab would be the basic options with all our checkboxes, and another tab the esthetics. When I do this it feels too crowded for a small window, and from platform to platform the tabs are displayed differently, even in vertical mode. For now, I'll have a toggle button that display the esthetics panel below the plot. We can revisit this at a later stage. 

Later I think we can maybe introduce some "icons" for features that can easily be understood with an icon. I like the idea of condensing the icons into python code using `PyEmbeddedImage` and [img2py](https://wxpython.org/Phoenix/docs/html/wx.tools.img2py.html)  as done [here](https://github.com/wxWidgets/Phoenix/blob/master/demo/images.py)
