### ISSUE TITLE
Multiple columns for nTabs

### ISSUE THREAD

**Issue by lobinho** [ebranlard/pyDatView#81]
Hi,

I was wondering why there is the restriction of forcing a single column selection with 2 or 3 different tables (len(ISel) > 1)? I suppose you had good reasons but it seems like a nice feature to do that.

The relevant section seems to be in GUISelectionPanel.py in method colSelectionChanged as shown below. Is it possible to avoid calling forceOneSelection or overcome this somehow?

` def colSelectionChanged(self):
        ...
                elif len(ISel)==2:
                    self.colPanel1.forceOneSelection()
                    ...
`

Cheers

**Comment by ebranlard** [comment]
Hi, 

I think the reasons for preventing different columns were that comparison and subplots wouldn't make as much sense, and maybe there was something about the logic to find the y-labels and the legends (there is a lot of ad-hoc logic to try to display either a ylabel or a legend, depending on the mode, and if the columns have the same names, or if they are from different tables etc.)..  

To be fair, at this point, I think these original restrictions can be lifted, I have found myself in situations were I was a bit frustrated by this limitation. 

If you want to try this, that's totally fine with me! You can start by commenting the 
forceOneSelection and see what happens :) Maybe you can add a "mode=nTabs_nCols" at first before removing the "nTabs_1Col", if that's of any help...

 Originally, I wanted to have the `PlotPanel` to be something that could be used and tested in a standalone fashion, and I wanted to have as little dependency between the `SelectionPanel` and the `GUIPlotPanel`.  I wanted the `PlotPanel` to be able to take a bunch of signals in and plot them. It still needs to know if signals comes from different tables to do the proper labelling and splitting of plots into subplots. The main interface to the `selectionPanel` is the very ugly `getPlotDataSelection`. I think in the future I'd like the PlotPanel to just take a list of `PlotData` as input, and add more and more logic that are not really related to the GUI into separate code (for instance the logic for legend labels). This way we can easily test the logic and corner cases with unittests.  Anyway, that was just a long digression to apologize for a lot of spaghetti code..

**Comment by lobinho** [comment]
Alright, thanks for the detailed reply. I will try adding this mode :)
