### ISSUE TITLE
Display Mean, Min and Max for zoomed in range, or between Meas 1 and Meas 2 markers

### ISSUE THREAD

**Issue by cdrtm** [ebranlard/pyDatView#90]
Would be great if there was an additional set of Mean, Min and Max that only reflect the visible portion of the graph after zoom. This would make it much easier to analyze waveforms by simply zooming in on specific areas.
An alternative solution would be to display Mean/Min/Max between Meas 1 and Meas 2.

**Comment by ebranlard** [comment]
Hi @Lodorand 
I can see that that could be useful. One way to achieve this with the current version is to use a Mask (Menu Data->Mask). For instance, setting the mask filter to: 
   ` {Time}>10`
or
  ` {Time}>10  & {Time}<20`
Let me know if that would work for your typical use cases. 
 
It's definitely not as interactive though as using the zoom. Computing the stats actually take a bit of time for huge datasets, but we can add a check box to do what you are thinking about.

**Comment by Lodorand** [comment]
Thanks for responding! Yes I did notice it was possible using the mask feature, though having to manually input the times makes it a little less convenient, especially when doing it repeatedly over multiple areas of the waveform.

Good point about the computation overhead, it would make the UI unresponsive if this feature was always enabled. A checkmark like you mentioned, or a "Calculate Zoomed Stats" on-demand button would work around that.

**Comment by cdrtm** [comment]
Thanks for merging!
