### ISSUE TITLE
Some suggestions for improvement

### ISSUE THREAD

**Issue by SimonHH** [ebranlard/pyDatView#91]
1. When switching axis to the right, with the matrix feature, y1 is not updated with AutoScale and the corsor position is only given for y1 and not for y2.
2. When selecting 3 tables with 1 being different in sensor to the others with auto mode selected: 3 Coloumns are given for sensorselection instead of 2. For comparing multiple tables with 2 or 3 sets of sensors it might help to check for each table if the sensors match to a different table.
3. Selected properties/statistics are reset after reloading. Prevent that?
4. Include a search for tables as it is possible for sensors. This helps when a lot of tables are loaded.
5. Save settings (e.g. selected sensors and other settings for display and data manipulation) to a settings file that can be loaded and applied to other tables.
6. Change the unit to wind engeneering units e.g. rad/s to rpm and Nm to kNm automatically or with a switch in the GUI.

In case I find time I will try and implement some of the items myself. Let me know what you think of the ideas.

**Comment by ebranlard** [comment]
Hi Simon, 

Thanks for the suggestions, here are some comments:

1. I'm not sure I can reproduce this issue. Can you describe it step by step so I can see what you mean?

2. I think that's more or less a feature. If you switch to the "3-tables" mode, do you get the behavior you want? I guess the auto mode makes it hard to know which table is which, right?

3. Yes, I agree, I've now created #92 for that. 

4. Interesting, that shouldn't be too too difficult. I've created #93.

5. In #13, I have in mind to generate the python script that reproduce the user manipulations. I actually started on that, but never got to finish it. I guess what you are suggesting would be related, but more for the GUI to repeat the user manipulation, some kind of "macro" save and apply. It might require quite some work... I personally think feature #13 wo

6. That's basically what I had in mind for #60 , so it's a good sign that you would also find this useful. I would likely do that via a menu, like "Data -> Wind Energy Units". Preferably, this would trigger a call to Table.py, that will convert all the columns values and units to the desired units.

I probably won't have time to look at those anytime soon. I think #60 could be a nice one to get familiar with the code. Maybe #92 and #93 too after that. Your help will be great!

**Comment by ebranlard** [comment]
I'm closing this, the only remaining item is #93
